spring:
  jpa:
    show-sql: true
    open-in-view: true
  h2:
    console:
      enabled: true
  jwt:
    secret: MySecret$12345
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB
file:
  upload-dir: /Users/kimyoowan/Desktop/files
