spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  jwt:
    secret: govlepel@$&
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB
file:
  upload-dir: /Users/kimyoowan/Desktop/files
